### ISSUE TITLE
Unclear about the user id, bot token, authorised user ids.

### ISSUE THREAD

**Issue by ashquest** [Simonx22/Google-Assistant-for-Telegram#5]
Hello Simonx22, in this line "Replace YOUR_ID with your own ID and YOUR_TOKEN with the token of the bot.", i cannot find YOUR_ID and YOUR_TOKEN. Do i have to replace it in the coding of program? I have the bot token but i don't understand the meaning of YOUR_ID.

And second thing, how can i get my device id(from my phone or from google website where i got device model id)

Please reply as soon as possible. I'll be very grateful to you and your project.

**Comment by imshahab** [comment]
> Hello Simonx22, in this line "Replace YOUR_ID with your own ID and YOUR_TOKEN with the token of the bot.", i cannot find YOUR_ID and YOUR_TOKEN. Do i have to replace it in the coding of program? I have the bot token but i don't understand the meaning of YOUR_ID.
> 
> And second thing, how can i get my device id(from my phone or from google website where i got device model id)
> 
> Please reply as soon as possible. I'll be very grateful to you and your project.

man I have the same question I can't understand where I can find my device id

**Comment by ashquest** [comment]
I figured it out. The device ID is just to identify the users using your Google Assistant so that Google can differentiate between different users. The device ID is useful in follow up questions. Its not something you get from Google, you actually define your own Device ID. It can be any string specific to the user.
